name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.19"
          cache: "npm"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: npm ci

      - name: Enable Angular cache
        run: npx ng config cli.cache.enabled true

      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build project
        run: npm run build